# Generated by Django 3.2.3 on 2021-07-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsno', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('rdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
